services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '3001:3001'
    env_file:
      - apps/server/.env
    restart: always
    networks:
      - tutribu-network
      - wordpress-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - /var/www/tutribu:/host/public
    command: sh -c "cp -r /app/public/. /host/public/ && while true; do sleep 3600; done"
    networks:
      - tutribu-network

networks:
  tutribu-network:
    driver: bridge
  wordpress-network:
    name: wordpress-0ppn_default
    external: true
